name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        ports:
          - 3308:3308
        options: > 
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          until docker exec app mysqladmin ping --host=db --user=root --password="${{ secrets.MYSQL_ROOT_PASSWORD }}" --silent &> /dev/null; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Run tests
        env:
          DB_HOST: db
          DB_USER: root
          DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_NAME: ${{ secrets.MYSQL_DATABASE }}
        run: |
          docker-compose exec app npm test

      - name: Shut down Docker Compose
        run: |
          docker-compose down
